export const ActionTypes = {
  MOVIES_LOADING: "MOVIE_LOADING",
  MOVIES_SUCCESS: "MOVIE_SUCCESS",
  MOVIES_ERROR: "MOVIE_ERROR",
  GENRES_LOADING:"GENRES_LOADING",
  GENRES_ERROR:"GENRES_ERROR",
  GENRES_SUCCESS:"GENRES_SUCCESS",
};
